language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install https://github.com/marrow/marrow.io.git#egg=marrow.io
  - pip install nose coverage
  - pip install -e . --use-mirrors
script: ./setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#webcore"
    on_success: change
    on_failure: change
